# This is a basic workflow to help you get started with Actions

name: EKS-WAS-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      RELEASE_NUMBER: ${{ github.run_number }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a Gradle build with JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      
      - name: Give permission to a gradlew file
        run: chmod +x ./gradlew
      
      - name: Source build to gradle
        run: |
          ./gradlew build --no-daemon
          ls -al ./build/libs
          cp ./build/libs/*.war ./Docker/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check Docker deamon
        run: docker ps

      - name: Docker image builld
        run: |
          cd ./Docker
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_v$RELEASE_NUMBER .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_v$RELEASE_NUMBER ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_v$RELEASE_NUMBER
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest

      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION_NAME }} --name ${{ secrets.AWS_USER_NAME }}

      - name: Deployment Rollout
        run: kubectl rollout restart deploy was-deployment

      - name: Rename file
        run: mv ./build/libs/my-spring-board-0.0.1-SNAPSHOT.war ./build/libs/backup-`date +%Y%m%d%H%M%S`.war 

      - name: S3 Upload
        run: aws s3 cp ./build/libs/*.war s3://${{ secrets.AWS_S3_BUCKET_NAME }}