# This is a basic workflow to help you get started with Actions

name: test2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a ls command
        run: ls -al

      # Runs a set of commands using the runners shell
      - name: Run a echo command
        run: echo "Hello World!"
        
      - name: Run a Gradle build with JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      
      - name: Give permission to a gradlew file
        run: chmod +x ./gradlew
      
      - name: Source build to gradle
        run: |
          ./gradlew build --no-daemon
          ls -al ./build/libs
          cp ./build/libs/*.war ./Docker/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check Docker deamon
        run: docker ps

      - name: Docker image builld
        run: |
          cd ./Docker
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest
